<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="MAIN" Id="{7405a2f5-75b3-4191-8a20-0eaa70ebfeae}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bSafeRun AT %Q*:BOOL;
	bErrAck AT %Q*:BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[bSafeRun;
bErrAck;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>